   version: 1.0

   tasks:
       hello:
           name: Hello World
           command: |
               echo "Hello, World!"
           triggeredBy:
           - manual
           - postEnvironmentStart  # Uncomment to run automatically after the environment starts

   services:
       backend:
           name: Backend Service
           description: Example service simulating a backend
           commands:
               start: |
                   echo "Starting backend service..."
                   touch /tmp/backend.started
                   while true; do
                       sleep 1
                       date
                   done
               ready: |
                   if [ -f /tmp/backend.started ]; then
                       echo "Backend service is ready"
                       exit 0
                   else
                       echo "Backend service is not ready"
                       exit 1
                   fi
               stop: |
                   echo "Stopping backend service..."
                   rm /tmp/backend.started
                   pkill -f "bash -c echo 'Starting backend service...'"  # Adjust this to match your start command
           triggeredBy:
               - postEnvironmentStart  # Uncomment to run automatically after the environment starts
